/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Dirent {
  readonly name: string
  readonly parentPath: string
  isFile(): boolean
  isDirectory(): boolean
  isSymbolicLink(): boolean
  isBlockDevice(): boolean
  isCharacterDevice(): boolean
  isFIFO(): boolean
  isSocket(): boolean
  get path(): string
}

export declare class Stats {
  readonly dev: number
  readonly mode: number
  readonly nlink: number
  readonly uid: number
  readonly gid: number
  readonly rdev: number
  readonly blksize: number
  readonly ino: number
  readonly size: number
  readonly blocks: number
  readonly atimeMs: number
  readonly mtimeMs: number
  readonly ctimeMs: number
  readonly birthtimeMs: number
  isFile(): boolean
  isDirectory(): boolean
  isSymbolicLink(): boolean
  isBlockDevice(): boolean
  isCharacterDevice(): boolean
  isFIFO(): boolean
  isSocket(): boolean
  /** Returns atime as a Date object (Node.js compatible) */
  get atime(): Date
  /** Returns mtime as a Date object (Node.js compatible) */
  get mtime(): Date
  /** Returns ctime as a Date object (Node.js compatible) */
  get ctime(): Date
  /** Returns birthtime as a Date object (Node.js compatible) */
  get birthtime(): Date
}

export declare function access(path: string, mode?: number | undefined | null): Promise<void>

export declare function accessSync(path: string, mode?: number | undefined | null): void

export declare function appendFile(
  path: string,
  data: string | Buffer,
  options?: WriteFileOptions | undefined | null,
): Promise<void>

export declare function appendFileSync(
  path: string,
  data: string | Buffer,
  options?: WriteFileOptions | undefined | null,
): void

export declare function chmod(path: string, mode: number): Promise<void>

export declare function chmodSync(path: string, mode: number): void

export declare function chown(path: string, uid: number, gid: number): Promise<void>

export declare function chownSync(path: string, uid: number, gid: number): void

export declare function copyFile(src: string, dest: string, mode?: number | undefined | null): Promise<void>

export declare function copyFileSync(src: string, dest: string, mode?: number | undefined | null): void

export declare function cp(src: string, dest: string, options?: CpOptions | undefined | null): Promise<void>

export interface CpOptions {
  recursive?: boolean
  force?: boolean
  errorOnExist?: boolean
  preserveTimestamps?: boolean
  dereference?: boolean
  verbatimSymlinks?: boolean
  /**
   * Vooya FS extension: number of parallel threads for recursive copy.
   * 0 or 1 means sequential; > 1 enables rayon parallel traversal.
   */
  concurrency?: number
}

export declare function cpSync(src: string, dest: string, options?: CpOptions | undefined | null): void

export declare function exists(path: string): Promise<boolean>

export declare function existsSync(path: string): boolean

export declare function glob(
  pattern: string,
  options?: GlobOptions | undefined | null,
): Promise<Array<string> | Array<Dirent>>

export interface GlobOptions {
  cwd?: string
  withFileTypes?: boolean
  exclude?: Array<string>
  concurrency?: number
  gitIgnore?: boolean
}

export declare function globSync(
  pattern: string,
  options?: GlobOptions | undefined | null,
): Array<string> | Array<Dirent>

export interface LineRange {
  from: number
  to: number
}

export declare function link(existingPath: string, newPath: string): Promise<void>

export declare function linkSync(existingPath: string, newPath: string): void

export declare function lstat(path: string): Promise<Stats>

export declare function lstatSync(path: string): Stats

export declare function mkdir(path: string, options?: MkdirOptions | undefined | null): Promise<string | undefined>

export interface MkdirOptions {
  recursive?: boolean
  mode?: number
}

export declare function mkdirSync(path: string, options?: MkdirOptions | undefined | null): string | undefined

export declare function mkdtemp(prefix: string): Promise<string>

export declare function mkdtempSync(prefix: string): string

export declare function readdir(
  path: string,
  options?: ReaddirOptions | undefined | null,
): Promise<Array<string> | Array<Dirent>>

/** * Reads the contents of a directory.
 * @param {string | Buffer | URL} path
 * @param {string | {
 *   encoding?: string;
 *   withFileTypes?: boolean;
 *   recursive?: boolean;
 *   }} [options]
 * @param {(
 *   err?: Error,
 *   files?: string[] | Buffer[] | Dirent[]
 * ) => any} callback
 * @returns {void}
 */
export interface ReaddirOptions {
  /**
   * File name encoding. 'utf8' (default) returns strings.
   * 'buffer' returns Buffer objects for each name.
   * Other values are treated as 'utf8'.
   */
  encoding?: string
  skipHidden?: boolean
  concurrency?: number
  recursive?: boolean
  withFileTypes?: boolean
}

export declare function readdirSync(
  path: string,
  options?: ReaddirOptions | undefined | null,
): Array<string> | Array<Dirent>

export declare function readFile(
  path: string,
  options?: string | ReadFileOptions | undefined | null,
): Promise<string | Buffer>

export interface ReadFileOptions {
  encoding?: string
  flag?: string
  lines?: LineRange
}

export declare function readFileSync(
  path: string,
  options?: string | ReadFileOptions | undefined | null,
): string | Buffer

export declare function readlink(path: string): Promise<string>

export declare function readlinkSync(path: string): string

export declare function realpath(path: string): Promise<string>

export declare function realpathSync(path: string): string

export declare function rename(oldPath: string, newPath: string): Promise<void>

export declare function renameSync(oldPath: string, newPath: string): void

export declare function rm(path: string, options?: RmOptions | undefined | null): Promise<void>

export declare function rmdir(path: string): Promise<void>

export declare function rmdirSync(path: string): void

/**
 * Removes files and directories (modeled on the standard POSIX `rm` utility).
 *
 * - `force`: When true, silently ignore errors when path does not exist.
 * - `recursive`: When true, remove directory and all its contents.
 * - `maxRetries`: If an `EBUSY`, `EMFILE`, `ENFILE`, `ENOTEMPTY`, or `EPERM` error is
 *   encountered, Node.js retries the operation with a linear backoff of `retryDelay` ms longer on
 *   each try. This option represents the number of retries.
 * - `retryDelay`: The amount of time in milliseconds to wait between retries (default 100ms).
 * - `concurrency` (vooya-fs extension): Number of parallel threads for recursive removal.
 */
export interface RmOptions {
  force?: boolean
  maxRetries?: number
  recursive?: boolean
  retryDelay?: number
  concurrency?: number
}

export declare function rmSync(path: string, options?: RmOptions | undefined | null): void

export declare function scan(root: string, options?: ScanOptions | undefined | null): Promise<Array<ScanEntry>>

export interface ScanEntry {
  /** Path relative to the scan root. */
  path: string
  name: string
  /** One of file, directory, symlink, or other. */
  kind: string
  size: number
  mode: number
  mtimeMs: number
  depth: number
}

export interface ScanOptions {
  /** Glob patterns rooted at `root`. Defaults to `**`. */
  include?: Array<string>
  /** Glob patterns to omit from the result. */
  exclude?: Array<string>
  /** Include matching directories as well as files. Defaults to false. */
  withDirectories?: boolean
  /** Follow symbolic links while walking and when collecting metadata. */
  followSymlinks?: boolean
  /** Apply .gitignore and other standard ignore files. Defaults to false. */
  gitIgnore?: boolean
  /** Skip hidden files and directories. Defaults to false. */
  skipHidden?: boolean
  /** Number of traversal threads. Zero selects the runtime heuristic. */
  concurrency?: number
}

export declare function scanSync(root: string, options?: ScanOptions | undefined | null): Array<ScanEntry>

export declare function stat(path: string): Promise<Stats>

export declare function statSync(path: string): Stats

export declare function symlink(target: string, path: string, symlinkType?: string | undefined | null): Promise<void>

export declare function symlinkSync(target: string, path: string, symlinkType?: string | undefined | null): void

export declare function truncate(path: string, len?: number | undefined | null): Promise<void>

export declare function truncateSync(path: string, len?: number | undefined | null): void

export declare function unlink(path: string): Promise<void>

export declare function unlinkSync(path: string): void

export declare function utimes(path: string, atime: number, mtime: number): Promise<void>

export declare function utimesSync(path: string, atime: number, mtime: number): void

export declare function writeFile(
  path: string,
  data: string | Buffer,
  options?: WriteFileOptions | undefined | null,
): Promise<void>

export interface WriteFileOptions {
  encoding?: string
  mode?: number
  flag?: string
}

export declare function writeFileSync(
  path: string,
  data: string | Buffer,
  options?: WriteFileOptions | undefined | null,
): void
